# Generated by Django 5.2.1 on 2025-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataTab1ToTab3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_num", models.IntegerField()),
                ("empId", models.CharField(max_length=200)),
                ("date_hire", models.DateField()),
                ("dob", models.DateField()),
                ("sex", models.IntegerField()),
                ("civil_status", models.IntegerField()),
                ("ip", models.IntegerField()),
                ("pwd", models.IntegerField()),
                ("solo_parent", models.IntegerField()),
                ("status", models.IntegerField()),
                ("effective_date", models.DateField()),
                ("employment_status", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("office_alias", models.CharField(max_length=200)),
                ("office_name", models.CharField(max_length=200)),
                ("division_name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("tenure_years", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sg", models.IntegerField()),
                ("job_level", models.CharField(max_length=200)),
                ("skills", models.CharField(max_length=500)),
            ],
        ),
    ]
