# Generated by Django 5.2.1 on 2025-06-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTab4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empId", models.IntegerField()),
                ("leave_type", models.IntegerField()),
                ("vl_reason", models.CharField(max_length=200)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("days_leave", models.IntegerField()),
                ("status", models.IntegerField()),
                ("sex", models.IntegerField()),
                ("age", models.IntegerField()),
                ("office_alias", models.CharField(max_length=200)),
                ("office_name", models.CharField(max_length=200)),
                ("division_name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
            ],
        ),
    ]
