# Generated by Django 5.2.1 on 2025-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_datatab5ot_datatab5travel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTab6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empId", models.CharField(max_length=200)),
                ("selected_form_text", models.CharField(max_length=200)),
                ("purpose", models.CharField(max_length=500)),
                ("others", models.CharField(max_length=400)),
                ("created_at", models.DateTimeField()),
                ("employment_status", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("office_alias", models.CharField(max_length=200)),
                ("office_name", models.CharField(max_length=200)),
                ("job_level", models.CharField(max_length=200)),
            ],
        ),
    ]
