# Generated by Django 5.2.1 on 2025-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_datatab6"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTab8",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empId", models.CharField(max_length=200)),
                ("converted_date", models.DateField()),
                ("title", models.CharField(max_length=500)),
                ("hours", models.IntegerField()),
                ("type", models.CharField(max_length=200)),
                ("international", models.CharField(max_length=200)),
                ("employment_status", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("office_alias", models.CharField(max_length=200)),
                ("job_level", models.CharField(max_length=200)),
            ],
        ),
    ]
