# Generated by Django 5.2.1 on 2025-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_datatab8"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTab9",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empId", models.CharField(max_length=200)),
                ("term", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("target_office", models.CharField(max_length=200)),
                ("competencies", models.CharField(max_length=500)),
                ("office_alias", models.CharField(max_length=200)),
                ("employment_status", models.CharField(max_length=200)),
            ],
        ),
    ]
