# Generated by Django 5.2.1 on 2025-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_datatab9"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataChurnRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empId", models.CharField(max_length=200)),
                ("office_alias", models.CharField(max_length=200)),
                ("tenure_years", models.DecimalField(decimal_places=2, max_digits=10)),
                ("risk_score", models.IntegerField()),
                ("risk_level", models.CharField(max_length=200)),
            ],
        ),
    ]
