# Generated by Django 5.2.1 on 2025-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_datachurnrisk"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTab7",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_position_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("type", models.CharField(max_length=200)),
                ("first", models.IntegerField()),
                ("second", models.IntegerField()),
                ("hired", models.IntegerField()),
                ("publication_title", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("sex", models.IntegerField()),
                ("civil_status", models.IntegerField()),
                ("level", models.CharField(max_length=200)),
                ("career", models.CharField(max_length=500)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
